apiVersion: v1
kind: Pod
metadata:
  name: evolving-pod
  labels:
    app: web-service
spec:
  containers:
    - name: web-server
      image: nginx:1.21
      ports:
        - containerPort: 80
      env:
        - name: ENV
          value: "production"
  restartPolicy: Always
