apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  key1: value1-changed
  key3: value3

---
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.22
      env:
        - name: CONFIG_KEY
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: key3
