apiVersion: v1
kind: Pod
metadata:
  name: shrinking-pod
  labels:
    app: microservice
spec:
  containers:
    - name: main-app
      image: node:18-alpine
      ports:
        - containerPort: 3000
      env:
        - name: NODE_ENV
          value: "production"
  restartPolicy: Always
