apiVersion: v1
kind: Pod
metadata:
  name: shrinking-pod
  labels:
    app: microservice
spec:
  containers:
    - name: main-app
      image: node:18-alpine
      ports:
        - containerPort: 3000
      env:
        - name: NODE_ENV
          value: "production"
    - name: monitoring-agent
      image: datadog/agent:latest
      env:
        - name: DD_API_KEY
          value: "secret-key"
  restartPolicy: Always
